services:
    APIGateway:
        build:
            context: ./APIGateway/
            dockerfile: Dockerfile
        image: apigateway
        restart: always
        networks:
            - auth
            - configuration
    ConfigurationService:
        build:
            context: ./ConfigurationService/
            dockerfile: Dockerfile
        image: configurationservice
        restart: always
        links:
            - APIGateway:api
            - ConfigurationServiceDB:database
        networks:
            - configuration
            - configurationdb
    ConfigurationServiceDB:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        networks:
            - configurationdb
        ports:
            - "5433:5432" #remove in production
    AuthService:
        build:
            context: AuthService/
            dockerfile: Dockerfile
        image: authservice
        restart: always
        links:
            - AuthServiceDB:database
            - APIGateway:api
        environment:
            - AUTH_JWT_SECRET=erifuhqiufhkifhilfuqfliwqghkwfgwakgwllwiu2qouofh3iufh34iuhweifbweiufhweof23hiugh #remove in production
            - DB_HOSTNAME=database
            - DB_PORT=5432
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        networks:
            - auth
            - authdb
        ports:
            - "8080:8080"
    AuthServiceDB:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        networks:
            - authdb
        ports:
            - "5432:5432" #remove in production

networks:
    auth:
        name: auth
    authdb:
        name: authdb
    configuration:
        name: configuration
    configurationdb:
        name: configurationdb
